BEGIN;

CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_role') THEN
    CREATE TYPE user_role AS ENUM ('MEMBER', 'ADMIN', 'SUPER_ADMIN');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'user_status') THEN
    CREATE TYPE user_status AS ENUM ('ACTIVE', 'INACTIVE', 'BLOCKED');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'deposit_status') THEN
    CREATE TYPE deposit_status AS ENUM ('REQUESTED', 'APPROVED', 'REJECTED');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'withdrawal_status') THEN
    CREATE TYPE withdrawal_status AS ENUM ('REQUESTED', 'COMPLETED', 'FAILED', 'CANCELED');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'product_subscription_status') THEN
    CREATE TYPE product_subscription_status AS ENUM ('ACTIVE', 'COMPLETED', 'CANCELED');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'ledger_entry_type') THEN
    CREATE TYPE ledger_entry_type AS ENUM (
      'DEPOSIT_APPROVED',
      'WITHDRAW_REQUESTED',
      'WITHDRAW_COMPLETED',
      'WITHDRAW_FAILED',
      'WITHDRAW_CANCELED',
      'PRODUCT_JOINED',
      'PRODUCT_DAILY_PROFIT',
      'PRODUCT_PRINCIPAL_RETURNED'
    );
  END IF;
END
$$;

CREATE TABLE IF NOT EXISTS users (
  id BIGSERIAL PRIMARY KEY,
  uid BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  login_id CITEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  name VARCHAR(80) NOT NULL,
  phone VARCHAR(30) NOT NULL,
  email CITEXT NOT NULL UNIQUE,
  role user_role NOT NULL DEFAULT 'MEMBER',
  status user_status NOT NULL DEFAULT 'ACTIVE',
  referrer_user_id BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
  usdt_address VARCHAR(300) NULL,
  level INTEGER NOT NULL DEFAULT 1,
  balance_available NUMERIC(36, 18) NOT NULL DEFAULT 0,
  balance_withdraw_locked NUMERIC(36, 18) NOT NULL DEFAULT 0,
  balance_product_principal NUMERIC(36, 18) NOT NULL DEFAULT 0,
  balance_total NUMERIC(36, 18) GENERATED ALWAYS AS (
    balance_available + balance_withdraw_locked + balance_product_principal
  ) STORED,
  email_verified_at TIMESTAMPTZ NULL,
  last_login_at TIMESTAMPTZ NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_users_uid ON users(uid);
CREATE INDEX IF NOT EXISTS idx_users_role_status ON users(role, status);

CREATE TABLE IF NOT EXISTS asset_policies (
  id BIGSERIAL PRIMARY KEY,
  network VARCHAR(20) NOT NULL DEFAULT 'TRC20',
  min_withdraw_amount NUMERIC(36, 18) NOT NULL DEFAULT 1,
  withdraw_allowed_weekdays SMALLINT[] NOT NULL DEFAULT ARRAY[0, 1, 2, 3, 4, 5, 6]::SMALLINT[],
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  effective_from TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_asset_policies_active ON asset_policies(is_active, effective_from DESC);
CREATE UNIQUE INDEX IF NOT EXISTS uq_asset_policies_network_effective_from ON asset_policies(network, effective_from);

CREATE TABLE IF NOT EXISTS deposits (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  network VARCHAR(20) NOT NULL,
  requested_amount NUMERIC(36, 18) NOT NULL CHECK (requested_amount > 0),
  txid VARCHAR(300) NOT NULL,
  proof_note TEXT NULL,
  status deposit_status NOT NULL DEFAULT 'REQUESTED',
  idempotency_key TEXT NOT NULL UNIQUE,
  requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  reviewed_at TIMESTAMPTZ NULL,
  reviewed_by BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
  approved_ledger_entry_id BIGINT NULL,
  admin_memo TEXT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_deposits_user_id ON deposits(user_id, id DESC);
CREATE INDEX IF NOT EXISTS idx_deposits_status ON deposits(status, id DESC);
CREATE INDEX IF NOT EXISTS idx_deposits_txid ON deposits(txid);

CREATE TABLE IF NOT EXISTS withdrawals (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  network VARCHAR(20) NOT NULL,
  requested_amount NUMERIC(36, 18) NOT NULL CHECK (requested_amount > 0),
  destination_address VARCHAR(300) NOT NULL,
  status withdrawal_status NOT NULL DEFAULT 'REQUESTED',
  idempotency_key TEXT NOT NULL UNIQUE,
  lock_ledger_entry_id BIGINT NULL,
  finalize_ledger_entry_id BIGINT NULL,
  chain_txid VARCHAR(300) NULL,
  admin_memo TEXT NULL,
  requested_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  reviewed_at TIMESTAMPTZ NULL,
  reviewed_by BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_withdrawals_user_id ON withdrawals(user_id, id DESC);
CREATE INDEX IF NOT EXISTS idx_withdrawals_status ON withdrawals(status, id DESC);

CREATE TABLE IF NOT EXISTS products (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  guide_text TEXT NOT NULL DEFAULT '',
  daily_rate NUMERIC(12, 8) NOT NULL DEFAULT 0.0001,
  profit_occurrence_limit INTEGER NOT NULL DEFAULT 30 CHECK (profit_occurrence_limit >= 0),
  profit_weekdays SMALLINT[] NOT NULL DEFAULT ARRAY[1, 2, 3, 4, 5]::SMALLINT[],
  return_principal BOOLEAN NOT NULL DEFAULT TRUE,
  is_visible BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_products_name ON products(name);

CREATE TABLE IF NOT EXISTS product_subscriptions (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
  participation_amount NUMERIC(36, 18) NOT NULL CHECK (participation_amount > 0),
  status product_subscription_status NOT NULL DEFAULT 'ACTIVE',
  joined_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  start_business_date DATE NOT NULL,
  remaining_profit_count INTEGER NOT NULL DEFAULT 0 CHECK (remaining_profit_count >= 0),
  completed_profit_count INTEGER NOT NULL DEFAULT 0 CHECK (completed_profit_count >= 0),
  total_profit_amount NUMERIC(36, 18) NOT NULL DEFAULT 0,
  request_idempotency_key TEXT NOT NULL UNIQUE,
  principal_lock_ledger_entry_id BIGINT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_product_subscriptions_user_id ON product_subscriptions(user_id, id DESC);
CREATE INDEX IF NOT EXISTS idx_product_subscriptions_status ON product_subscriptions(status, id DESC);

CREATE TABLE IF NOT EXISTS ledger_entries (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  entry_type ledger_entry_type NOT NULL,
  amount NUMERIC(36, 18) NOT NULL DEFAULT 0,
  delta_available NUMERIC(36, 18) NOT NULL DEFAULT 0,
  delta_withdraw_locked NUMERIC(36, 18) NOT NULL DEFAULT 0,
  delta_product_principal NUMERIC(36, 18) NOT NULL DEFAULT 0,
  reference_type VARCHAR(80) NULL,
  reference_id BIGINT NULL,
  business_date DATE NOT NULL,
  idempotency_key TEXT NOT NULL UNIQUE,
  note TEXT NULL,
  created_by BIGINT NULL REFERENCES users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ledger_entries_user_id ON ledger_entries(user_id, id DESC);
CREATE INDEX IF NOT EXISTS idx_ledger_entries_business_date ON ledger_entries(business_date DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_ledger_entries_reference ON ledger_entries(reference_type, reference_id);

COMMIT;
